services:
  dashly:
    image: lklynet/dashly:latest
    ports:
      - "${PORT:-8080}:8080" # User-configurable via .env
    environment:
      - NGINX_DB_PATH=/nginx/database.sqlite # Must not change
      - USER_SETTINGS_FILE=/data/settings.json # Must not change
    volumes:
      - ${NGINX_DB_PATH}:/nginx/database.sqlite:ro # External database
      - ${USER_SETTINGS:-./data}:/data # Defaults to internal ./data
    restart: unless-stopped
    env_file:
      - .env # Recommended for customization
