services:
  dashly:
    image: dashly:local
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ${NGINX_DB_PATH}:/data/database.sqlite:ro
      - ${USER_SETTINGS}:/data/user_settings.db
    restart: unless-stopped
