services:
  dashly:
    image: lklynet/dashly
    ports:
      - "8080:8080"
    volumes:
      - ${NGINX_DB_PATH}:/nginx/database.sqlite:ro
      - ${USER_SETTINGS}:/data
    restart: unless-stopped
